name: Linux

on: [push]

jobs:
  ci:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php:
          - '8.3-alpine'
          - '8.3-zts-alpine'
          - '8.2-alpine'
          - '8.2-zts-alpine'
          - '8.1-alpine'
          - '8.1-zts-alpine'
        image: [php]
        include:
          - php: '8.0-alpine'
            image: ghcr.io/kjdev/php
          - php: '7.4-alpine'
            image: ghcr.io/kjdev/php
          - php: '7.3-alpine'
            image: ghcr.io/kjdev/php
          - php: '7.2-alpine'
            image: ghcr.io/kjdev/php
          - php: '7.1-alpine'
            image: ghcr.io/kjdev/php
          - php: '7.0-alpine'
            image: ghcr.io/kjdev/php

    container:
      image: ${{ matrix.image }}:${{ matrix.php }}

    steps:
      - name: Prepare required command
        run: |
          apk upgrade --no-cache
          apk add --no-cache autoconf gcc g++ git libtool make musl-dev automake

      - name: Install dependency library
        run: |
          git clone --depth=1 https://github.com/ssdeep-project/ssdeep.git
          cd ssdeep
          ./bootstrap
          ./configure
          make 
          make install

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: |
          phpize
          ./configure
          make      

      - name: Test
        run: |
          make test TESTS="--show-diff" | tee test-output.txt
          grep 'TEST SUMMARY$' test-output.txt > /dev/null && exit 1 || exit 0
        env:
          REPORT_EXIT_STATUS: 1
          NO_INTERACTION: 1

      - name: Failure Test
        run: |
          for FILE in $(find ./tests -name '*.diff'); do
            echo echo $FILE
            cat $FILE
            echo
          done
        if: ${{ failure() }}